name: Build single file pyinstaller

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    permissions: write-all
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.10']

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller requests tabulate

    - name: Build executable
      run: |
        cd src
        pyinstaller --onefile main.py -n livefield

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: executable-${{ matrix.os }}
        path: |
          src/dist/livefield
          src/dist/livefield.exe

    - name: Create Windows Release
      uses: "softprops/action-gh-release@v2"
      if: ${{ matrix.os == 'windows-latest'}}
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        tag_name: "windows-latest"
        prerelease: true
        name: "Windows Development Build"
        body: "Windows development description field"
        files: |
          README.md
          src/dist/livefield.exe
          ex_config.json
          jsconfig.json

    - name: Create Ubuntu Release
      uses: "softprops/action-gh-release@v2"
      if: ${{ matrix.os == 'ubuntu-latest'}}
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        tag_name: "ubuntu-latest"
        prerelease: true
        name: "Ubuntu Development Build"
        body: "Ubuntu development description field"
        files: |
          README.md
          src/dist/livefield
          ex_config.json
          jsconfig.json

